### PR TITLE
add CHD support and rework cd image loading / reading

### LINKED ISSUE #34: Add CHD support to 4DO [Bounty]
This is a follow-up to a previous bounty.

All I ask is that someone adds CHD support to the 4DO

The bounty will be $15.

I realize that the 3DO isn't the most popular console, but I thought I might as well make this bounty to cover the last RetroArch core that uses compact discs (excluding PicoDrive, which I might make a bounty for later).

### PR DESCRIPTION
**Pull request by trapexit**
It doesn't appear there are any libretro standard libraries to manage
CDROM images. While such a thing would be useful in the long run for
this change I've imported the pce fast deps used by libchdr and
libretro-common's chd_stream.

closes #34

### CODE REVIEW

**Comment by Darknior** [comment]
Hoooo excellent, thanks a lot for this update :)
I love the idea to reduce all my ISO ...

If i remember fine CHD compress but not support multi CD files in one. Like PBP on PSX where we can do it and it's really better to manage our collection.
Do you know it's possible to found a solution for it ?
Thanks

**Comment by hizzlekizzle** [comment]
@Darknior the other cores rely on m3u playlists of CHDs, which seems to work pretty well. It's just a bog-standard txt file with one CHD per line.

**Comment by trapexit** [comment]
This change doesn't include any multi disc / m3u support. I'd have to see what it means to do so in other cores. Is it to share save files? I recently added shared NVRAM feature which would handle that generally.

**Comment by hizzlekizzle** [comment]
@trapexit yeah, it's to streamline sharing save files across discs and for swapping discs. If you already have it covered, it's probably not worth worrying about.

**Comment by Darknior** [comment]
@hizzlekizzle hooo excellent, i know m3u files but i never think to try them lol
I will try them on MegaCD ans NecCD :)
It change nothing to swap disk when i must insert "Disc 2" ?

**Comment by hizzlekizzle** [comment]
@Darknior yeah, for the cores that support them, you just go into the cd drive options and open the try, go to next disc, go out of the menu for a few seconds, come back, close the tray and then go back to game. We're getting off topic from the PR, though, so if you run into problems, just open a thread at the forums.

**Comment by UltimoCs** [comment]
I have a feeling this broke .cue file loading.  std isos still work ok but loading from cue just fails with "failed to load content"

**Comment by trapexit** [comment]
Will take a look.

**Comment by trapexit** [comment]
Need more information.

What version of chdman? What was the command line arguments used?

I just took chdman from ubuntu (version 0.195) and ran:
```
$ chdman createcd -o test.chd -i "Road Rash.iso"
```

It loaded up fine.

**Comment by bebess** [comment]
i test with chdman v4 and chdman 0.189 , i dont test with another version
i do the same command line
i do all my chd (pcengine/segacd/tg16cd) with the version 0.189 for windows and all games work with no problem,

i try the last version (0.196) and same problem

my games are in bin+cue , maybe it's the problem ? i ll try with an iso

**Comment by bebess** [comment]
ok i test one game in iso format and compress the game to chd
and it works , the game launch

if i do the same with the game in bin+cue formant and compresse the game to chd
the game dont launch

**Comment by trapexit** [comment]
It appears chdman packs the files differently. I was able to get it to work but I need to figure out how to auto detect the situation.

**Pull request merged**
