### PR TITLE
replace __cplusplus externing checks with macro

### PR DESCRIPTION
**Pull request by trapexit**
Simplifies the code and helps with some IDE indentation algos.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hmm, can't say I am a big fan of this.

If you do insist on doing this, why not use retro_common_api.h's RETRO_BEGIN_DECLS/RETRO_END_DECLS? At least then we'd not be reinventing the wheel.

**Comment by trapexit** [comment]
Didn't know it existed and hadn't noticed it used by other cores while skimming them. However in this case I think it's preferred to keep it separate. I'm trying to keep a clean separation between the core emulator code and the libretro glue so the former can still be used by others with minimal effort.

If you'd prefer not to be a contention point for all the changes I have queued up that are entirely aimed at improving the emulator code I can do all the development in my own repo and we can merge later. The reason I've been using the libretro version of 4do for my changes is because it's the only active version around at the moment and the one I use.

**Comment by twinaphex** [comment]
Alright, as long as we keep the codebase plain C I don't mind. Guess I'll merge it.

**Comment by trapexit** [comment]
I'll be keeping it C. Like I said the changes really aren't libretro related and I'm fine with moving development outside of libretro till the cleanup is finished if that'd be easier. Effectively working upstream and then merging back down. I just didn't want to drop a complete rewrite on you without notice.

**Comment by twinaphex** [comment]
> Like I said the changes really aren't libretro related and I'm fine with moving development outside of libretro till the cleanup is finished if that'd be easier. Effectively working upstream and then merging back down.

There is no reason to do that honestly, you are welcome to push these changes.

**Comment by twinaphex** [comment]
If you want, you can get direct push access rights so that you can push directly to this repo in case that'd make things easier.

**Comment by trapexit** [comment]
I just want to make sure we're on the same page regarding my plans and I wasn't sure if non-libretro specific development was OK. I imagine most of the time you're sinking non-libretro changes from some upstream repo. 

As for access to the repo... sure. That'll give me a bit more control over the flow of changes. That said I'm going to try to make these changes as incrementally as possible so its easy to follow.

**Comment by twinaphex** [comment]
Sourceforge says that 4DO repo was last updated in 2016, and the last few commits it had were mostly tinkerings on their C# frontend code which honestly has no relevance to this libretro core. 

Anyway, I'll be giving you commit access.

**Comment by trapexit** [comment]
Agreed. The alternative to working directly with the 4do-libretro repo was to just work within my fork of it on github more independently than I've been doing recently and then work to sync up later. I've been chatting with the 4do team lead and explained what I was doing. He's supportive.

**Comment by twinaphex** [comment]
OK, so with you now having direct commit access, we can continue development as we have been doing so far? I'd be most in favor of that.

**Comment by trapexit** [comment]
Yup, will do. Thanks.

**Comment by twinaphex** [comment]
No problem, thanks for leading this initiative in improving 3DO emulation.

**Pull request merged**
