### PR TITLE
rewrite NVRAM handling, add shared NVRAM mode

### PR DESCRIPTION
**Pull request by trapexit**
Sorry for the big diff. Decided to update libretro-common to get some newer functions and did some minor cleanup. More thorough cleanup to come in a future pull request.

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, one minor reservation though - we can probably remove the libretro-common files we don't need and just limit it to the ones we do require. Is it fine for me to remove the source files we don't need later on after merging this?

**Comment by trapexit** [comment]
I can remove them.

**Comment by twinaphex** [comment]
Alright, are you planning to use any more of them or will you only use the currently used ones in this PR?

**Comment by trapexit** [comment]
Not entirely sure yet. I plan on attempting a major cleanup of the code and there might be some things I can replace with libretro-common versions but I've not seriously looked into what they may be yet.

**Comment by twinaphex** [comment]
I'm afraid there is no better way yeah.

If you want I can do this manually for you. I'd just create my own commit.

**Comment by trapexit** [comment]
I just reverted the libretro-common change completely and added specifically what I needed. I'll include any changes to it in the cleanup pr.

**Comment by twinaphex** [comment]
Ah, I already made my own commit and pushed it to master. Let me know if it includes everything you wanted to include in this PR. If it does, we could close this.

**Comment by twinaphex** [comment]
There are two commits BTW.

**Comment by trapexit** [comment]
Shouldn't really every push straight to master. Best to make changes on branches and merge in. Regardless besides a small change I just made I think its fine.

**Comment by twinaphex** [comment]
Anyway, can we close this PR then and you just send me a separate PR where we merge in whatever small change you had made since starting this PR?

**Comment by trapexit** [comment]
I'm not sure I understand what's to disagree about. Besides merge to master being an antipattern we've lost authorship, comments, history, etc.

Alright. I'll rebase and submit.

**Comment by twinaphex** [comment]
> Besides merge to master being an antipattern 

I'm sorry but I have run this project for the past 7/8+ years, and things are fine here in this regard. I don't care about some supposed best practice here, I have ran this project for the better part of 7/8+ years and I think I have managed it fairly well enough to know which pattern is worth following and which isn't.

> we've lost authorship, comments, history, etc.

Maybe halfway valid points, however, I consider that worth the tradeoff if the alternative is merging in a ton of files that is going to make git cloning this repo take forever vs. what it was before. If this whole massive merging of libretro-common files hadn't been done, I could have merged your PR as-is. As it was, it had too many downsides in its current form.

It was not done by malicious intent at least to commit those things, but honestly, just merging this PR in its current form would have bloated repo size severely.

**Pull request closed without merging**
